version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vitrine_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/BANCO_VITRINE.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: