-- Adicionar novas colunas à tabela PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN SUBCATEGORIA VARCHAR(50);
ALTER TABLE PRODUTOS ADD COLUMN TAMANHO VARCHAR(10);
ALTER TABLE PRODUTOS ADD COLUMN QUANTIDADE INT DEFAULT 1;
ALTER TABLE PRODUTOS ADD COLUMN BUSTO_P VARCHAR(20);
ALTER TABLE PRODUTOS ADD COLUMN COMP_P VARCHAR(20);
ALTER TABLE PRODUTOS ADD COLUMN BUSTO_M VARCHAR(20);
ALTER TABLE PRODUTOS ADD COLUMN COMP_M VARCHAR(20);
ALTER TABLE PRODUTOS ADD COLUMN BUSTO_G VARCHAR(20);
ALTER TABLE PRODUTOS ADD COLUMN COMP_G VARCHAR(20);