-- SCRIPT COMPLETO PARA RAILWAY
-- Execute este script inteiro no seu banco Railway

-- Criar tabela USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    EMAIL_USUARIO VARCHAR(35) UNIQUE NOT NULL,
    CELULAR_USUARIO VARCHAR(15),
    LOGRADOURO_USUARIO VARCHAR(100),
    BAIRRO_USUARIO VARCHAR(30),
    CIDADE_USUARIO VARCHAR(30),
    UF_USUARIO VARCHAR(2),
    CEP_USUARIO VARCHAR(8),
    DT_NASC_USUARIO DATE,
    SENHA_USUARIO VARCHAR(255) NOT NULL,
    TIPO_USUARIO VARCHAR(10) NOT NULL,
    IMAGEM_PERFIL_BASE64 LONGTEXT
);

-- Criar tabela CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CPF_CLIENTE CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT UNSIGNED NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

-- Criar tabela VENDEDORES
CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TIPO_PESSOA CHAR(2) NOT NULL, 
    DIGITO_PESSOA VARCHAR(14) UNIQUE NOT NULL,
    NOME_LOJA VARCHAR(100),
    ID_USUARIO INT UNSIGNED NOT NULL, 
    IMAGEM_PERFIL_LOJA_BASE64 LONGTEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

-- Criar tabela ADMINISTRADORES
CREATE TABLE ADMINISTRADORES (
    ID_ADM INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CPF_ADM CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT UNSIGNED NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

-- Criar tabela CATEGORIAS
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(100) NOT NULL 
);

-- Criar tabela PRODUTOS com TODAS as colunas necessárias
CREATE TABLE PRODUTOS (
    ID_PROD INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_PROD VARCHAR(120) NOT NULL,
    VALOR_UNITARIO DECIMAL(6,2) NOT NULL,
    DESCRICAO_PROD VARCHAR(250),
    IMAGEM_URL VARCHAR(2048),
    IMAGEM_BASE64 LONGTEXT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Campos de categoria e vendedor
    ID_CATEGORIA INT UNSIGNED, 
    ID_VENDEDOR INT UNSIGNED NOT NULL,
    
    -- Novos campos para roupas
    SUBCATEGORIA VARCHAR(50),
    TAMANHO VARCHAR(10),
    QUANTIDADE INT DEFAULT 1,
    
    -- Tabela de tamanhos
    BUSTO_P VARCHAR(20),
    COMP_P VARCHAR(20),
    BUSTO_M VARCHAR(20),
    COMP_M VARCHAR(20),
    BUSTO_G VARCHAR(20),
    COMP_G VARCHAR(20),
    
    -- Foreign keys
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

-- Criar tabela PEDIDOS
CREATE TABLE PEDIDOS (
    ID_PEDIDO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT UNSIGNED NOT NULL,
    DT_PEDIDO DATE NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

-- Inserir categorias básicas
INSERT INTO CATEGORIAS (NOME_CATEGORIA) VALUES 
('Artesanato'),
('Decoração'),
('Roupas'),
('Acessórios');

-- Criar usuário admin padrão (senha: 123456)
INSERT INTO USUARIOS (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, TIPO_USUARIO) VALUES 
('Admin', 'admin@vitrine.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin');