CREATE TABLE USUARIOS (
    ID_USUARIO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    EMAIL_USUARIO VARCHAR(35) UNIQUE NOT NULL,
    CELULAR_USUARIO CHAR(11) UNIQUE NOT NULL,
    LOGRADOURO_USUARIO VARCHAR(100) NOT NULL,
    BAIRRO_USUARIO VARCHAR(30) NOT NULL,
    CIDADE_USUARIO VARCHAR(30) NOT NULL,
    UF_USUARIO VARCHAR(2) NOT NULL,
    CEP_USUARIO VARCHAR(8) NOT NULL,
    DT_NASC_USUARIO DATE NOT NULL,
    SENHA_USUARIO CHAR(6) NOT NULL,
    TIPO_USUARIO CHAR(1) NOT NULL
);

ALTER TABLE USUARIOS
MODIFY COLUMN SENHA_USUARIO
VARCHAR (255) NOT NULL;

ALTER TABLE USUARIOS ADD COLUMN IMAGEM_PERFIL_BASE64 LONGTEXT;

ALTER TABLE USUARIOS MODIFY COLUMN CELULAR_USUARIO VARCHAR(15);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CPF_CLIENTE CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT UNSIGNED NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TIPO_PESSOA CHAR(2) NOT NULL, 
    DIGITO_PESSOA VARCHAR(14) UNIQUE NOT NULL,
    ID_USUARIO INT UNSIGNED NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

ALTER TABLE VENDEDORES ADD COLUMN IMAGEM_PERFIL_LOJA_BASE64 LONGTEXT;

CREATE TABLE ADMINISTRADORES (
    ID_ADM INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CPF_ADM CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT UNSIGNED NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(100) NOT NULL 
);

CREATE TABLE PRODUTOS (
    ID_PROD INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_PROD VARCHAR(120) UNIQUE NOT NULL,
    VALOR_UNITARIO DECIMAL(6,2) NOT NULL,
    DESCRICAO_PROD VARCHAR(250) UNIQUE NOT NULL,
    ID_CATEGORIA INT UNSIGNED, 
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
);

ALTER TABLE PRODUTOS ADD COLUMN IMAGEM_URL VARCHAR(2048);
ALTER TABLE PRODUTOS ADD COLUMN ID_VENDEDOR INT UNSIGNED NOT NULL;
ALTER TABLE PRODUTOS ADD CONSTRAINT fk_vendedor FOREIGN KEY (ID_VENDEDOR) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE;
ALTER TABLE PRODUTOS ADD COLUMN DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PRODUTOS ADD COLUMN IMAGEM_BASE64 LONGTEXT;

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT UNSIGNED NOT NULL,
    DT_PEDIDO DATE NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);


CREATE TABLE PRODUTOS_VENDEDORES (
    ID_PROD INT UNSIGNED NOT NULL,
    ID_VENDEDOR INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PROD, ID_VENDEDOR), 
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS (ID_PROD),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES (ID_VENDEDOR)
);

CREATE TABLE PEDIDOS_CATEGORIAS (
    ID_PEDIDO INT UNSIGNED NOT NULL,
    ID_CATEGORIA INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_CATEGORIA),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
);


CREATE TABLE PEDIDOS_PRODUTOS (
    ID_PEDIDO INT UNSIGNED NOT NULL,
    ID_PROD INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_PROD), -- Chave primária composta
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS (ID_PROD)
);

CREATE TABLE PRODUTOS_HAS_CATEGORIAS (
    ID_PROD INT UNSIGNED NOT NULL,
    ID_CATEGORIA INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PROD, ID_CATEGORIA),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS (ID_PROD),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
);

CREATE TABLE CLIENTES_HAS_PEDIDOS ( 
    ID_CLIENTE INT UNSIGNED NOT NULL,
    ID_PEDIDO INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_CLIENTE, ID_PEDIDO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
);